---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /bin/systemd

provisioner:
  name: puppet_apply
  resolve_with_librarian_puppet: false
  manifests_path: manifests
  resolve_with_r10k: false
  puppet_debug: true
  puppet_verbose: true
  require_chef_for_busser: true
  require_puppet_omnibus: true
  require_puppet_repo: false
  #
  modules_path: modules:.modules
  require_chef_for_busser: false
  #
  # name: puppet_bolt
  # bolt_version: 2.40.2  # last that works with ruby <2.5.3 (1804)
  # bolt_modulepath:  modules;.modules
  #


platforms:
  - name: ubuntu-18.04
    driver_config:
      image: ubuntu:bionic
      platform: ubuntu

busser:
  sudo: true

verifier:
  name: inspec

suites:
  - name: snakepit-head
    provisioner:
      custom_options: '-e "include roles::snakepit_head"'
  #     bolt_commands:
  #     - bolt --help
  #     - bolt --version
  #     - bolt apply manifests/snakepit_head.pp
  #     - bolt task show
  # # - name: snakepit-worker
