---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /bin/systemd

provisioner:
  name: puppet_apply
  hiera_data_path: data
  hiera_data_remote_path: /tmp/kitchen/data
  hiera_deep_merge: true
  resolve_with_librarian_puppet: false
  manifests_path: manifests
  resolve_with_r10k: false
  puppet_debug: true
  puppet_verbose: true
  require_chef_for_busser: true
  require_puppet_omnibus: true
  require_puppet_repo: false
  #
  modules_path: modules:.modules
  #
  # name: puppet_bolt
  # bolt_version: 2.40.2  # last that works with ruby <2.5.3 (1804)
  # bolt_modulepath:  modules;.modules
  #


platforms:
  - name: ubuntu-18.04
    driver_config:
      image: ubuntu:bionic
      platform: ubuntu

busser:
  sudo: true

verifier:
  name: inspec

suites:
  - name: snakepit-head
    driver:
      publish_all: true
      instance_name: mlchead_kitchen
    driver_config:
      hostname: mlchead.kitchen
    provisioner:
      custom_options: '-e "include roles::snakepit_head"'
  - name: snakepit-worker
    driver:
      # send queries for mlchead to mlchead_kitchen container
      links: "mlchead_kitchen:mlchead"
    driver_config:
      hostname: mlc0.kitchen
    provisioner:
      custom_options: '-e "include roles::snakepit_worker"'

  # kitchen-puppet puppet_bolt options
  #     bolt_commands:
  #     - bolt --help
  #     - bolt --version
  #     - bolt apply manifests/snakepit_head.pp
  #     - bolt task show
  # how does it get hostname (to run locally)? or how do files get to the host (to run remotely)?
